# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_sub_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_background'),
        ),
    ]
