# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160314_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_background', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
